### ISSUE TITLE
ModuleNotFoundError: No module named 'obfuscators.powershell.chameleon.chameleon'

### ISSUE THREAD

**Issue by fuzz-security** [klezVirus/inceptor#4]
PS C:\Users\test\Desktop\inceptor\inceptor> python3 .\inceptor.py
Traceback (most recent call last):
  File "C:\Users\test\Desktop\inceptor\inceptor\inceptor.py", line 12, in <module>
    from generators.PowerShellArtifactGenerator import PowerShellArtifactGenerator
  File "C:\Users\test\Desktop\inceptor\inceptor\generators\PowerShellArtifactGenerator.py", line 9, in <module>
    from obfuscators.powershell.Karmaleon import Karmaleon
  File "C:\Users\test\Desktop\inceptor\inceptor\obfuscators\powershell\Karmaleon.py", line 6, in <module>
    from obfuscators.powershell.chameleon.chameleon import Chameleon
ModuleNotFoundError: No module named 'obfuscators.powershell.chameleon.chameleon'

**Comment by klezVirus** [comment]
Hi fuzz-security, I guess you forgot the --recursive flag.

Whoever reading this message: check the install section.

```
git clone --recursive https://github.com/klezVirus/inceptor
``` 
If you haven't clone with recursive, you can still fix it, with this:
```
cd inceptor\inceptor\obfuscator\powershell
git clone https://github.com/klezVirus/chameleon
```
After that, you will probably need to fix the `.gitmodule` file as windows usually use the "\\" path divider instead of "/".
